### ISSUE TITLE
怎么把eslint关掉，把lintOnSave设置为false，就报错了，服务启动不了

### ISSUE THREAD

**Issue by gesha96** [wellfrog16/template-vue-admin#2]
INFO  Starting development server...
 ERROR  TypeError: Cannot set property 'emitError' of undefined
TypeError: Cannot set property 'emitError' of undefined
    at config.module.rule.use.loader.tap (d:\learnCode\vue-admin\template-vue-admin-master\vue.config.js:77:34)
    at Object.tap (d:\learnCode\vue-admin\template-vue-admin-master\node_modules\webpack-chain\src\Use.js:14:20)
    at chainWebpack (d:\learnCode\vue-admin\template-vue-admin-master\vue.config.js:75:14)
    at webpackChainFns.forEach.fn (d:\learnCode\vue-admin\template-vue-admin-master\node_modules\@vue\cli-service\lib\Service.js:227:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (d:\learnCode\vue-admin\template-vue-admin-master\node_modules\@vue\cli-service\lib\Service.js:227:26)
    at Service.resolveWebpackConfig (d:\learnCode\vue-admin\template-vue-admin-master\node_modules\@vue\cli-service\lib\Service.js:231:48)
    at PluginAPI.resolveWebpackConfig (d:\learnCode\vue-admin\template-vue-admin-master\node_modules\@vue\cli-service\lib\PluginAPI.js:138:25)
    at serve (d:\learnCode\vue-admin\template-vue-admin-master\node_modules\@vue\cli-service\lib\commands\serve.js:48:31)
    at Service.run (d:\learnCode\vue-admin\template-vue-admin-master\node_modules\@vue\cli-service\lib\Service.js:221:12)
    at Object.<anonymous> (d:\learnCode\vue-admin\template-vue-admin-master\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by wellfrog16** [comment]
参看 #1
